#!/usr/bin/env node
/*
 * generate-tokens.mjs — DS-3 token pipeline for Nyxite.
 *
 * Reads the single source of truth (nyxite-tokens.json — a STYLE GUIDE of
 * values, not a component spec) and emits per-platform *style* artifacts so no
 * client hand-copies a hex or a dp. It generates values only; components are
 * implemented natively per client.
 *
 *   node tools/generate-tokens.mjs           # write dist/**
 *   node tools/generate-tokens.mjs --check   # CI drift check: exit 1 if dist/** is stale
 *
 * Zero dependencies (pure Node fs). Outputs:
 *   dist/web/tokens.css              CSS custom properties (:root + dark overrides)
 *   dist/web/tailwind.tokens.cjs     Tailwind theme.extend referencing the CSS vars
 *   dist/android/values/colors.xml   palette + status + light semantic colors
 *   dist/android/values-night/colors.xml   dark semantic colors (auto-swaps)
 *   dist/android/values/dimens.xml   spacing + radius + border widths (dp)
 *   dist/desktop/Tokens.axaml        Avalonia ResourceDictionary w/ Light+Dark ThemeDictionaries
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const SRC = join(ROOT, 'nyxite-tokens.json');
const DIST = join(ROOT, 'dist');
const CHECK = process.argv.includes('--check');

const T = JSON.parse(readFileSync(SRC, 'utf8'));
const BANNER = `GENERATED by tools/generate-tokens.mjs from nyxite-tokens.json v${T.version} — do not edit by hand.`;

// ---- naming helpers ----
const kebab = (s) => String(s).replace(/([a-z0-9])([A-Z])/g, '$1-$2').toLowerCase();
const snake = (s) => kebab(s).replace(/-/g, '_');
const pascal = (s) => String(s).replace(/(^|[-_])([a-z0-9])/g, (_, __, c) => c.toUpperCase());
const familyList = (s) => s.split(',').map((x) => x.trim());

const { palette, semantic, status } = T.color;
const outputs = {};

// ---------------------------------------------------------------- web: CSS
function buildCss() {
  const L = [`/* ${BANNER} */`, ':root {'];
  const push = (k, v) => L.push(`  ${k}: ${v};`);

  for (const [ramp, val] of Object.entries(palette)) {
    if (typeof val === 'string') push(`--palette-${kebab(ramp)}`, val);
    else for (const [step, hex] of Object.entries(val)) push(`--palette-${kebab(ramp)}-${step}`, hex);
  }
  for (const [k, hex] of Object.entries(status)) push(`--status-${kebab(k)}`, hex);
  for (const [k, hex] of Object.entries(semantic.light)) push(`--color-${kebab(k)}`, hex);
  for (const [k, v] of Object.entries(T.shadow.light)) push(`--shadow-${kebab(k)}`, v);

  push('--font-ui', T.typography.fontFamily.ui);
  push('--font-serif', T.typography.fontFamily.serif);
  for (const [k, w] of Object.entries(T.typography.fontWeight)) push(`--font-weight-${kebab(k)}`, w);
  for (const [k, v] of Object.entries(T.spacing.scale)) push(`--space-${k}`, `${v}px`);
  for (const [k, v] of Object.entries(T.radius)) push(`--radius-${kebab(k)}`, `${v}px`);
  for (const [k, v] of Object.entries(T.borderWidth)) push(`--border-${kebab(k)}`, `${v}px`);
  for (const [k, v] of Object.entries(T.motion.duration)) push(`--duration-${kebab(k)}`, `${v}ms`);
  for (const [k, v] of Object.entries(T.motion.easing)) push(`--ease-${kebab(k)}`, v);
  L.push('}');

  const darkVars = (ind) => [
    ...Object.entries(semantic.dark).map(([k, hex]) => `${ind}--color-${kebab(k)}: ${hex};`),
    ...Object.entries(T.shadow.dark).map(([k, v]) => `${ind}--shadow-${kebab(k)}: ${v};`),
  ].join('\n');

  L.push('', '/* Follow OS preference unless an explicit theme is set */');
  L.push('@media (prefers-color-scheme: dark) {', '  :root:not([data-theme="light"]) {', darkVars('    '), '  }', '}');
  L.push('', '/* Explicit toggle wins in both directions */');
  L.push('[data-theme="dark"] {', darkVars('  '), '}');
  return L.join('\n') + '\n';
}

// ---------------------------------------------------------- web: Tailwind
function buildTailwind() {
  const colors = {};
  for (const k of Object.keys(semantic.light)) colors[kebab(k)] = `var(--color-${kebab(k)})`;
  for (const k of Object.keys(status)) colors[`status-${kebab(k)}`] = `var(--status-${kebab(k)})`;
  const paletteColors = {};
  for (const [ramp, val] of Object.entries(palette)) {
    if (typeof val === 'string') paletteColors[kebab(ramp)] = `var(--palette-${kebab(ramp)})`;
    else {
      paletteColors[kebab(ramp)] = {};
      for (const step of Object.keys(val)) paletteColors[kebab(ramp)][step] = `var(--palette-${kebab(ramp)}-${step})`;
    }
  }
  const spacing = Object.fromEntries(Object.entries(T.spacing.scale).map(([k, v]) => [k, `${v}px`]));
  const radius = Object.fromEntries(Object.entries(T.radius).map(([k, v]) => [kebab(k), `${v}px`]));
  const shadow = Object.fromEntries(Object.keys(T.shadow.light).map((k) => [kebab(k), `var(--shadow-${kebab(k)})`]));
  const theme = {
    extend: {
      colors: { ...colors, palette: paletteColors },
      spacing,
      borderRadius: radius,
      boxShadow: shadow,
      fontFamily: { ui: familyList(T.typography.fontFamily.ui), serif: familyList(T.typography.fontFamily.serif) },
      transitionDuration: Object.fromEntries(Object.entries(T.motion.duration).map(([k, v]) => [k, `${v}ms`])),
    },
  };
  return `/* ${BANNER} */\nmodule.exports = { theme: ${JSON.stringify(theme, null, 2)} };\n`;
}

// ------------------------------------------------------------ android: XML
function buildAndroidColors(theme) {
  const L = ['<?xml version="1.0" encoding="utf-8"?>', `<!-- ${BANNER} -->`, '<resources>'];
  if (theme === 'light') {
    for (const [ramp, val] of Object.entries(palette)) {
      if (typeof val === 'string') L.push(`  <color name="${snake(ramp)}">${val}</color>`);
      else for (const [step, hex] of Object.entries(val)) L.push(`  <color name="${snake(ramp)}_${step}">${hex}</color>`);
    }
    for (const [k, hex] of Object.entries(status)) L.push(`  <color name="status_${snake(k)}">${hex}</color>`);
  }
  for (const [k, hex] of Object.entries(semantic[theme])) L.push(`  <color name="${snake(k)}">${hex}</color>`);
  L.push('</resources>');
  return L.join('\n') + '\n';
}
function buildAndroidDimens() {
  const L = ['<?xml version="1.0" encoding="utf-8"?>', `<!-- ${BANNER} -->`, '<resources>'];
  for (const [k, v] of Object.entries(T.spacing.scale)) L.push(`  <dimen name="space_${k}">${v}dp</dimen>`);
  for (const [k, v] of Object.entries(T.radius)) L.push(`  <dimen name="radius_${snake(k)}">${v}dp</dimen>`);
  for (const [k, v] of Object.entries(T.borderWidth)) L.push(`  <dimen name="border_${snake(k)}">${v}dp</dimen>`);
  L.push('</resources>');
  return L.join('\n') + '\n';
}

// ------------------------------------------------------------ desktop: AXAML
function buildAvalonia() {
  const themeDict = (name, key) => {
    const L = [`    <ResourceDictionary x:Key="${name}">`];
    for (const [k, hex] of Object.entries(semantic[key])) {
      L.push(`      <Color x:Key="${pascal(k)}Color">${hex}</Color>`);
      L.push(`      <SolidColorBrush x:Key="${pascal(k)}Brush" Color="${hex}"/>`);
    }
    L.push('    </ResourceDictionary>');
    return L.join('\n');
  };
  const L = [
    '<ResourceDictionary xmlns="https://github.com/avaloniaui" xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">',
    `  <!-- ${BANNER} -->`,
    '  <ResourceDictionary.ThemeDictionaries>',
    themeDict('Light', 'light'),
    themeDict('Dark', 'dark'),
    '  </ResourceDictionary.ThemeDictionaries>',
    '',
    '  <!-- Theme-independent: palette, status, dimensions -->',
  ];
  for (const [ramp, val] of Object.entries(palette)) {
    if (typeof val === 'string') L.push(`  <Color x:Key="Palette${pascal(ramp)}">${val}</Color>`);
    else for (const [step, hex] of Object.entries(val)) L.push(`  <Color x:Key="Palette${pascal(ramp)}${step}">${hex}</Color>`);
  }
  for (const [k, hex] of Object.entries(status)) L.push(`  <Color x:Key="Status${pascal(k)}">${hex}</Color>`);
  for (const [k, v] of Object.entries(T.spacing.scale)) L.push(`  <x:Double x:Key="Space${k}">${v}</x:Double>`);
  for (const [k, v] of Object.entries(T.radius)) L.push(`  <x:Double x:Key="Radius${pascal(k)}">${v}</x:Double>`);
  for (const [k, v] of Object.entries(T.borderWidth)) L.push(`  <x:Double x:Key="Border${pascal(k)}">${v}</x:Double>`);
  L.push('</ResourceDictionary>');
  return L.join('\n') + '\n';
}

// ---------------------------------------------------------------- assemble
outputs['web/tokens.css'] = buildCss();
outputs['web/tailwind.tokens.cjs'] = buildTailwind();
outputs['android/values/colors.xml'] = buildAndroidColors('light');
outputs['android/values-night/colors.xml'] = buildAndroidColors('dark');
outputs['android/values/dimens.xml'] = buildAndroidDimens();
outputs['desktop/Tokens.axaml'] = buildAvalonia();

// ------------------------------------------------------------- write/check
if (CHECK) {
  const drift = [];
  for (const [rel, content] of Object.entries(outputs)) {
    const p = join(DIST, rel);
    if (!existsSync(p) || readFileSync(p, 'utf8') !== content) drift.push(rel);
  }
  if (drift.length) {
    console.error('Token drift — dist/ is stale. Run: node tools/generate-tokens.mjs\n' + drift.map((d) => '  dist/' + d).join('\n'));
    process.exit(1);
  }
  console.log('Tokens up to date.');
} else {
  for (const [rel, content] of Object.entries(outputs)) {
    const p = join(DIST, rel);
    mkdirSync(dirname(p), { recursive: true });
    writeFileSync(p, content);
  }
  console.log(`Generated ${Object.keys(outputs).length} files into dist/.`);
}
